

# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.

version: 0.0
# Specify "os: linux" if this revision targets Amazon Linux
os: linux

files:
  - source: /
    destination: /home/ec2-user/server

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  # During the BeforeInstall deployment lifecycle event, run the commands
  #   in the script specified in "location".
  BeforeInstall:
    - location: index.html 
      timeout: 1000
   
  # During the AfterInstall deployment lifecycle event, run the commands
  #   in the script specified in "location".
  AfterInstall:
    - location: index.html 
      timeout: 1600
 

  # During the ApplicationStart deployment lifecycle event, run the commands
  #   in the script specified in "location".
  ApplicationStart:
    - location: index.html 
      timeout: 300


